name: parcels_v4_10yr_event
channels:
  - https://repo.prefix.dev/parcels
  - conda-forge
dependencies:
  - python =3.12
  - parcels = 4
  - copernicusmarine >= 2

  # Kernel workshop dependencies
  - plotly

  # v4 tutorial
  - gsw
